services:
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 delivery_tracking.wsgi:application
    volumes:
      - .:/app
      - static_files:/app/static:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=delivery_tracking_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=wolcott123!
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_DB=delivery_tracking_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=wolcott123!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.24.0-alpine3.17-slim
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount the Nginx config file
      - static_files:/var/www/static:ro
    depends_on:
      - api

volumes:
  postgres_data:
  static_files:
