# Generated by Django 5.0.3 on 2024-03-11 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='login_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='NO NAME', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
