# Generated by Django 5.0.3 on 2024-03-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_crate_id_crate_crate_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
