# Generated by Django 5.0.3 on 2024-03-27 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_allocation',
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='allocated_slots',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VehicleAllocation',
        ),
    ]
