# Generated by Django 5.0.3 on 2024-04-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_vehicle_vehicle_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_batches', to='core.customer'),
            preserve_default=False,
        ),
    ]
