# Generated by Django 5.0.3 on 2024-04-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_deliverybatch_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='current_vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle', to='core.driver'),
        ),
    ]
