# Generated by Django 5.0.3 on 2024-04-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_driver_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
