# Generated by Django 5.0.3 on 2024-04-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_contact_login_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crate',
            name='contents',
        ),
    ]
