# Generated by Django 5.0.6 on 2024-05-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_deliverybatch_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofofdelivery',
            name='delivery_batch',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_delivery', models.TimeField(auto_now_add=True)),
                ('date_of_delivery', models.DateField(auto_now_add=True)),
                ('crates', models.ManyToManyField(related_name='deliveries', to='core.crate')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.driver')),
                ('proof_of_delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='core.proofofdelivery')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.vehicle')),
            ],
        ),
    ]
